### ISSUE TITLE
Collect usage examples

### ISSUE THREAD

**Issue by aleneum** [pytransitions/transitions#280]
- [ ] condition-based transition (#269)
- [ ] check conditions before returning possible transitions with `get_triggers` (#256)
- [ ] show how `MachineCore` (wip) can be used to reduce the memory footprint when using Django (#146)
